### PR TITLE
Remove "typings" directory and use types directly

### LINKED ISSUE #338: textlint: remove "typings" directory and use types directly
https://github.com/textlint/textlint/tree/master/typings should be removed.
It is wrong types.

We already have correct type #332 

**Changes**

- Add `types` field to `package.json` of `textlint` module.

**Blocker**

- textlint: index.ts export as es module #337

### PR DESCRIPTION
**Pull request by Leko**
Fixed #338

### CODE REVIEW

**Comment by azu** [comment]
Probably, txtast.md refer to typing/*d.ts for documentation.
We need to prepare alternative one.

@textlint/kernel includes same types definition with typings. But that definiton files is not under the git.

**Comment by azu** [comment]
> We need to prepare alternative one.

Ah, [txtnode.md](https://github.com/textlint/textlint/blob/master/docs/txtnode.md "txtnode.md") include copy of definition.
We can just remove link to `typings/*.dts` from [txtnode.md](https://github.com/textlint/textlint/blob/master/docs/txtnode.md "txtnode.md").

@Leko Please remove link in [txtnode.md](https://github.com/textlint/textlint/blob/master/docs/txtnode.md "txtnode.md")

     [TxtAST](../typings/txtast.d.ts) interface

and remove text

    Please see TypeScript definition file: typings/txtast.ts

and remove link

    [`TxtNode`](../typings/txtast.ts) has these properties.

**Comment by Leko** [comment]
@azu Thank you for review.
I got it. I'll update soon.

**Comment by azu** [comment]
@Leko Super Fast! Thanks again.

**Pull request merged**
