### PR TITLE
docs(readme): delete --global in readme Closes #885

### LINKED ISSUE #885: Install `--global` contradicts reccomendation
On the [Installation section of the README](https://github.com/textlint/textlint#installation), the installation command is: 

```
$ npm install textlint --global
```

However, a few lines below, the library recommends:  
> We recommend installing `textlint` locally.

Most people will install globally after copy/pasting and not read past to this reccomendation.

Suggestion: remove `--global` from README

### PR DESCRIPTION
**Pull request by Uda-Titor**
resolve https://github.com/textlint/textlint/issues/885

### CODE REVIEW

**Comment by azu** [comment]
Thanks for PR.

If install textlint locally, `textlint` is not found in global.
So, we need to care about`textlint` command in usage.

For example, use `npx textlint`.
https://github.com/textlint/textlint/blob/af45282e5cdf7e86cb2548b5ccf6164a49734876/README.md?plain=1#L81
Also, I recommened to use `npm install --save-dev`.

Another option: create `create-textlint` package and use it with `npm init` or `yarn create` like ESLint.

- [Getting Started with ESLint - ESLint - Pluggable JavaScript Linter](https://eslint.org/docs/latest/user-guide/getting-started)
  - [eslint/create-config: Utility to create ESLint config files](https://github.com/eslint/create-config)

**Comment by Uda-Titor** [comment]
@azu 
Thank you for your advise.
I took your advice.

Review again please!

**Comment by azu** [comment]
> If install textlint locally, `textlint` is not found in global.
> So, we need to care about`textlint` command in usage.

It looks like not resolved.

**Comment by azu** [comment]
Thanks.
I've created follow up issue #900

**Pull request merged**
