### PR TITLE
refactor(textlint-formatter): move to @textlint/linter-formatter

### PR DESCRIPTION
**Pull request by 0x6b**
Ref #455.

Note: I did not change CLI name from `textlint-formatter` to `linter-formatter` for compatibility. I think `textlint-formatter` is more intuitive name for users, but if you think `linter-formatter` is better, please let me know and I will update this pull request as follows:

1. Add `linter-formatter.js` to `bin/` directory
2. Add above to `package.json#bin` as key `linter-formatter`
3. (Optional?) Add deprecate message while running `textlint-formatter` (`bin/cmd.js`)

Need major version bump as it will break CI build. Thanks.

### CODE REVIEW

**Comment by azu** [comment]
> (Optional?) Add deprecate message while running textlint-formatter (bin/cmd.js)

No. Runtime message break exiting behavior.

Instead of it, You can deprecate old module by executing following command: 

```
npm deprecate textlint-formatter "See https://github.com/textlint/textlint/issues/455"
```

As as result, show deprecated message in installing time.

```
npm install textlint-formatter 
# show deprecated message
```

**Comment by azu** [comment]
> Need major version bump as it will break CI build.

Yes and No.
These are difference name, but the API is same.
So, It does not require major update.

> ℹ️ Migration information for user
> https://github.com/textlint/textlint/issues/455

**Comment by 0x6b** [comment]
@azu, appreciate your comments. I missed update (and detailed!) description at #455. Run `npm deprecate` then merge the pull request. Thank you very much.

**Comment by 0x6b** [comment]
For the record:
```
$ npm deprecate textlint-formatter "See https://github.com/textlint/textlint/issues/455"
$ npm info --json textlint-formatter | jq .deprecated
"See https://github.com/textlint/textlint/issues/455"
```

**Pull request merged**
