### PR TITLE
chore(yarn): add yarn-check scripts

### LINKED ISSUE #386: Add `yarn check --integrity` in `yarn test`
Currently, The difference between `yarn.lock` and pacakge.json is ignored.
(CI doesn't fail)

We can check the difference by [yarn check --integrity](https://yarnpkg.com/lang/en/docs/cli/check/ "yarn check") command.

## Workflow

Does check the difference between `yarn.lock` and `package.json` dependencies.

```
yarn check --integrity
```

If the command is failed, Run `yarn run bootstrap` that update `yarn.lock`.

## Proposal

Add `yarn-check` command to `pacakge.json`

```
"test": "npm-run-all --parallel yarn-check lint test:packages",
// ...   
"yarn-check": "yarn check --integrity || echo 'Please run yarn bootstrap'"
```

**Problem**

This proposal has a problem.
It is always to be exit code `0` and, maybe, it is not compatible with cross platform.
We want to improve this.

```
✈ yarn check --integrity || echo 'Please run yarn bootstrap'
yarn check v1.3.2
warning Integrity check: Lock files don't match
error Integrity check failed
error Found 1 errors.
info Visit https://yarnpkg.com/en/docs/cli/check for documentation about this command.
Please run yarn bootstrap

~/.ghq/github.com/textlint/textlint master*
✈ echo $?
0
```

### PR DESCRIPTION
**Pull request by azu**
image

> [yarn install --frozen-lockfile](https://yarnpkg.com/en/docs/cli/install#toc-yarn-install-frozen-lockfile "yarn install --frozen-lockfile")
> Don’t generate a yarn.lock lockfile and fail if an update is needed.

> [yarn check --integrity](https://yarnpkg.com/en/docs/cli/check "yarn check --integrity")
> Verifies that versions and hashed value of the package contents in the project’s package.json matches that of yarn’s lock file. This helps to verify that the package dependencies have not been altered.

- [x] Add `precommit` hook instread of `prepush`
- [x] Add `yarn install --frozon-lockfile` to `travis.yml` 
- [x] Add `yarn install --frozon-lockfile` to `appveyor.yml`

fix #386

### CODE REVIEW

**Comment by azu** [comment]
The motivation of the change is no more unnecessary updating `yarn.lock` after `yarn install` or `yarn bootstrap`
Often, we do `yarn bootstrap` in local, and make a diff of `yarn.lock`.

[yarn check --integrity](https://yarnpkg.com/lang/en/docs/cli/check/ "yarn check --integrity") verify the diff.
But, I don't know that is best solution.

**Comment by 0x6b** [comment]
@azu, I found that `yarn.lock` differenes you found at commit 92f20ba was introduced at my pull request #417 (add `examples/use-as-ts-module`). I added new dependency to the project with the PR but I intentionally didn't commit `yarn.lock` at that moment since I thought:

1. `package.json` is the canonical source of package dependencies, and
2. `yarn.lock` is derived/auto-generated metafile based on `package.json`

TIL: "[Lockfiles should be committed on all projects](https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/)" and my ignorance of `yarn.lock` changes might cause installation instability. Sorry for that 😰 

My thoughts for next step:

- To prevent out-of-sync `yarn.lock` issue, run `yarn check --integrity` at `.git/hooks/pre-commit` so that we could make sure contributor can review changes when it fails
- Add [`--frozen-lockfile`](https://yarnpkg.com/en/docs/cli/install#toc-yarn-install-frozen-lockfile) (don't generate a yarn.lock lockfile and fail if an update is needed) in CI setup

Maybe I'm missing something. Appreciate your thoughts. Thank you!

Related discussion:

- [`yarn install --frozen-lockfile` should be the default behavior · Issue #4147 · yarnpkg/yarn](https://github.com/yarnpkg/yarn/issues/4147)
- [yarn.lock is always "touched" on install, although contents is unmodified · Issue #4912 · yarnpkg/yarn](https://github.com/yarnpkg/yarn/issues/4912)

**Comment by 0x6b** [comment]
@azu, as I said I missed something :(

> - Add yarn-check into prepush

This seems identical to my comment (run `yarn check --integrity` at `pre-commit` hook). I missed we have Husky 🐶. I think the solution does not always prevent `yarn.lock` update, but will make sure unintentional `package.json` change won't commit to the repo.

> - Add yarn-check in CI

`yarn install --frozon-lockfile` or `yarn check` on CI environment could detect integrity issue. Probably this leads to CI only failure.

**Comment by azu** [comment]
@0x6b Thanks for details comment!

- [ ] Add `precommit` hook instread of `prepush`
- [ ] Add `yarn install --frozon-lockfile` to `travis.yml`

**Comment by 0x6b** [comment]
LGTM!

**Pull request merged**
