### PR TITLE
feat(core):  sort messages by line and column

### LINKED ISSUE #126: sort messages by line and column
We'll  sort message by line and column.

- https://github.com/textlint/textlint/blob/0ed7087810f6c266e60a73105ed752f8e4a3afd4/src/textlint-core.js#L99-L106

Add the sort like this:

```js
        // sort by line and column
        messages.sort(function(a, b) {
            var lineDiff = a.line - b.line;

            if (lineDiff === 0) {
                return a.column - b.column;
            } else {
                return lineDiff;
            }
        });
```

### PR DESCRIPTION
**Pull request by azu**
fix #126

### CODE REVIEW

**Comment by azu** [comment]
FYI: https://github.com/1000ch/linter-textlint sometime display wrong order.
This pull request fix this issue.

**Comment by azu** [comment]
@homu r+

**Comment by io-monad** [comment]
Could this break the existing tests for rules? Requires major version up?

My rule plugin got failed after updated textlint to 5.6.0
https://github.com/io-monad/textlint-rule-general-novel-style-ja/pull/7

I'm using `textlint-tester` and the failed test case is:

```
        {
            text: "「こんにちは、世界。。。」",
            output: "「こんにちは、世界」",
            errors: [
                {
                    message: "句読点(。、)が閉じ括弧の直前に存在しています",
                    line: 1,
                    column: 12
                },
                {
                    message: "連続した句読点(。、)が使われています",
                    line: 1,
                    column: 10
                }
            ]
        },
```

**Comment by azu** [comment]
@io-monad fmm.. I think that it is a implementation dependent(should be fixed), but the change break the test case.
I've reverted these commits and release 6.1.1.

https://github.com/textlint/textlint/commit/3651f9df61738d1ab49752885138cf436d8675e5
https://github.com/textlint/textlint/commit/106da2f7fa8ae927266df346cbbc89759417c6f7

**Comment by io-monad** [comment]
@azu Yes, I agree that it should be fixed and definitely I will do. Or maybe textlint-tester can take care of the order of messages.

However, IMO changing the order of messages is not "in backwards-compatible manner" described in semver.

Anyway thanks for quick response!

**Comment by azu** [comment]
It is better that One rule check One matter.
If you want to check multiple rule in a single module, I recommened that using preset system.

**Comment by io-monad** [comment]
fmm, okay. I'll try splitting rules into local submodules like `textlint-rule-preset-JTF-style`. But I think plugin's name stays the same... (without officially recommended "textlint-rule-preset-" prefix). :sweat_smile:

I can say a rule preset may have tests for a conjunction of multiple sub-rules and may fail like this problem anyway, can't I? Or a rule preset should have no tests for conjunctions?

**Comment by io-monad** [comment]
No, we don't need fix the test case for 6.1.0... :weary:

**Comment by azu** [comment]
> :memo: It is better that One rule check One matter.

In other word, It is _Single Responsibility Principle_.

> I can say a rule preset may have tests for a conjunction of multiple sub-rules and may fail like this problem anyway, can't I? Or a rule preset should have no tests for conjunctions?

There are not official testing tool :bow: 
Can we need to add testing function like `runPreset` to [textlint-tester](https://github.com/textlint/textlint-tester "textlint-tester")?

**Comment by azu** [comment]
We try again this  #218

**Pull request merged**
