### PR TITLE
feat(textlint): add `padding` property and `locator` 

### LINKED ISSUE #835: RFC: Improve error location
Parts of #833

Currently, error message has only start position(`line` and `column` or `index`).
It prevents that underline actual error text.

Some editor plugin requires the full locations includes start and end.

Proposal

- Add `locator` function and `location` property
    - `locator` has `.range([number, number)` and `.location({ start, end })`
    - bike shading name

```js
const reporter = (context) => {
    const { Syntax, RuleError, fixer, locator, report, getSource } = context;
    return {
        [Syntax.Str](node) {
            const text = getSource(node);
            const matchRegexp = /\bfix\b/;
            if (!matchRegexp.test(text)) {
                return;
            }
            const index = text.search(matchRegexp);
            const length = "fix".length;
            report(
                node,
                new RuleError("Replaced", {
                    location: locator.range([index, index + length])
                })
            );
        }
    };
};
export default {
    linter: reporter,
    fixer: reporter
};
```

### PR DESCRIPTION
**Pull request by azu**
## Changes

- Add `loc` and `range` property to `TextlintMessage`(result)
- Add `padding` prorperty to `RuleError(message, details)`.
- Add `locator` object to rule's context
	- `lcoator.at(index)`, `locator.range([startIndex, endIndex])`, and `locator.loc({ start: { line, column }, end: { line, column }})`.
- Deprecate `index`, `line` and `column` property on `TextlintMessage` and `report` function
	- Preserve current behavior for backward compatible
- Update `filterMessages` to use new `range` property on `TextlintMessage`
- Use  `readonly [number, number]` as range in all packages
- Fix `filterMessages` bug https://github.com/textlint/textlint/pull/836/commits/c8a670f9b4fd7ce628a940dc4c8faabd5e62d396
- Refactor tests
- Update rule.md documentation
  - Add `padding` and `locator` object
  - Add `peerDependencies` note

textlint v12.2.0 will introduce `padding` and `locator`.
If your will use it, please add `peerDependencies` to `package.json` on your rule package.

```json5
  "peerDependencies": {
    "textlint": ">= 12.2.0"
  }
```

## For textlint rule creator

Before:

```js
const { Syntax, report, RuleError } = context;
// .....
report(node, new RuleError(message, {
  index: 1
}));
```

After:

```js
const { Syntax, report, RuleError, locator } = context;
// .....
report(node, new RuleError(message, {
  padding: locator.range([1, 2])
}));
```

## Internal Workflow

- [x] refactor SourceLocation
- [x] implement `padding` and `locator`
- [x] fallback: convert `index`, `colimn`, `line` to `loc` info
- [x] Update textlint-tester
- [x] Update Document
- [ ] Add Migration Guide(Tool?)

fix #835

### CODE REVIEW

**Comment by azu** [comment]
- [ ] add loc validation
- [ ] update documentation
- [ ] add snapshot testing

**Comment by azu** [comment]
We need to think about `filterMessages` Logics

Previously, `index` and `column`/`line` is a single point.
However, `range` and `loc` are area.

```
Ignored Range:              |___________|
Matched A:                         |______| 
Matched B:                                    |______| 
Matched C:               |______| 
Matched D:                    |___________| 
```

- A: should be ignored
- B: ?
- C: ?
- C: should be ignored

https://github.com/textlint/textlint/blob/0503af68f4a34beaab2e45c34463ad4e0e24a958/packages/%40textlint/kernel/src/messages/filter-ignored-process.ts#L12-L15

**Comment by azu** [comment]
We do not ignore E.
B and C is near case to E.
So, We should not ignore B and C, E.

Conclusion:

- A: Ignore
- B: Error
- C: Error
- D: Ignore
- E: Error

**Comment by azu** [comment]
- [ ] Update Document
- [ ] Add Migration Guide

**Comment by azu** [comment]
no-todo migration

Before

```ts
import { TextlintRuleContext, TextlintRuleReportHandler } from "@textlint/types";
import { RuleHelper } from "textlint-rule-helper";
export default function (context: TextlintRuleContext): TextlintRuleReportHandler {
    const helper = new RuleHelper(context);
    const { Syntax, getSource, RuleError, report } = context;
    return {
        /*
            # Header
            Todo: quick fix this.
        */
        [Syntax.Str](node) {
            if (helper.isChildNode(node, [Syntax.Link, Syntax.Image, Syntax.BlockQuote])) {
                return;
            }
            // get text from node
            const text = getSource(node);
            // does text contain "todo:"?
            const match = text.match(/todo:/i);
            if (match) {
                report(
                    node,
                    new RuleError(`Found TODO: '${text}'`, {
                        index: match.index
                    })
                );
            }
        },
        /*
            # Header
            - [ ] Todo
        */
        [Syntax.ListItem](node) {
            const text = context.getSource(node);
            const match = text.match(/\[\s+\]\s/i);
            if (match) {
                report(
                    node,
                    new context.RuleError(`Found TODO: '${text}'`, {
                        index: match.index
                    })
                );
            }
        }
    };
}
```


After

```ts
import { TextlintRuleContext, TextlintRuleReportHandler } from "@textlint/types";
import { RuleHelper } from "textlint-rule-helper";

export default function(context: TextlintRuleContext): TextlintRuleReportHandler {
    const helper = new RuleHelper(context);
    const { Syntax, getSource, RuleError, report, locator } = context;
    return {
        /*
            # Header
            Todo: quick fix this.
        */
        [Syntax.Str](node) {
            if (helper.isChildNode(node, [Syntax.Link, Syntax.Image, Syntax.BlockQuote])) {
                return;
            }
            // get text from node
            const text = getSource(node);
            // does text contain "todo:"?
            const match = text.match(/todo:/i);
            if (match && match.index !== undefined) {
                report(
                    node,
                    new RuleError(`Found TODO: '${text}'`, {
                        loc: locator.range([match.index, match.index + match[0].length])
                    })
                );
            }
        },
        /*
            # Header
            - [ ] Todo
        */
        [Syntax.ListItem](node) {
            const text = context.getSource(node);
            const match = text.match(/\[\s+\]\s/i);
            if (match && match.index !== undefined) {
                report(
                    node,
                    new context.RuleError(`Found TODO: '${text}'`, {
                        loc: locator.range([match.index, match.index + match[0].length])
                    })
                );
            }
        }
    };
}
```

**Comment by azu** [comment]
It is better that `loc` property will be `padding` property, I think.

**Comment by trusktr** [comment]
Hello @azu! I see you mentioned https://github.com/tc39/ecma262/issues/45#issuecomment-1001298248 up above. Was that intentional? If so, how does this relate to that?

**Comment by azu** [comment]
Ah, That is mistake.

**Comment by azu** [comment]
After release, We need to update [textlint-rule-en-max-word-count](https://github.com/azu/textlint-rule-en-max-word-count "textlint-rule-en-max-word-count") and following documents

- [ ] rule-advanced.md
- [ ] rule-fixable.md

**Pull request merged**
