### PR TITLE
Removes CLI from @textlint/linter-formatter

### LINKED ISSUE #1222: Remove CLI from @textlint/linter-formatter
@textlint/linter-formatter has a CLI, but it is not used.

We will remove the CLI from `@textlint/linter-formatter` in v14

- #1200

### PR DESCRIPTION
**Pull request by kapooraryan**
Closes #1222 

Changes made following the Contribution guide.

### CODE REVIEW

**Comment by azu** [comment]
Thanks.

📝 It will be a BREAKING CHANGE and must be merged just before the next major update.

**Comment by kapooraryan** [comment]
> Thanks.
> 
> 📝 It will be a BREAKING CHANGE and must be merged just before the next major update.

Sure, when will this update take place?

**Comment by azu** [comment]
No specific timetable has been set yet.

**Comment by azu** [comment]
I'm working on the next major version, V14.

Thanks for PR

**Pull request merged**
