### PR TITLE
refactor(kernel): replace assert with invariant function

### LINKED ISSUE #985: Migrate assert to invariant function
We want to reduces deps in @textlint/kernel.

Node.js `assert` is extra dependencies for browser.
https://github.com/search?q=repo%3Atextlint%2Ftextlint+assert+path%3A%2F%5Epackages%5C%2F%40textlint%5C%2Fkernel%5C%2F%2F+path%3A%2F%5Epackages%5C%2F%40textlint%5C%2Fkernel%5C%2Fsrc%5C%2F%2F&type=code&l=packages%2F%40textlint%2Fkernel%2Fsrc%2F

So, We use `invariant` instead of `assert.ok` in kernel.

```ts
function invariant(condition: any, message: string): asserts condition {
    if (condition) {
        return;
    }
    throw new Error(message);
}

```

### PR DESCRIPTION
**Pull request by Sean0628**
This PR tries to remove a redundant dependency on assert module by replacing assert.ok with the self-defined invariant function.

Closes #985

### After the change
```sh
>>> rg assert ./packages/@textlint/kernel/src
./packages/@textlint/kernel/src/descriptor/TextlintLintableRuleDescriptor.ts
4:import { assertRuleShape, getLinter } from "./rule-creator-helper";
14:        assertRuleShape(textlintKernelRule.rule, textlintKernelRule.ruleId);

./packages/@textlint/kernel/src/descriptor/README.md
38:assert.deepStrictEqual(descriptors.plugin.availableExtensions, [".txt", ".md"]);
41:assert.ok(markdownProcessor !== undefined);
43:assert.strictEqual(descriptors.rule.descriptors.length, 1);

./packages/@textlint/kernel/src/descriptor/rule-creator-helper.ts
77:export function assertRuleShape(ruleModule: any, key: string = "") {

./packages/@textlint/kernel/src/core/source-location.ts
29:const assertReportArgs = (reportArgs: Pick<TextlintRuleContextReportFunctionArgs, "node" | "ruleError" | "ruleId">) => {
49:    // when running from textlint-tester, assert
346:    assertReportArgs(args);

./packages/@textlint/kernel/src/util/invariant.ts
8:export function invariant(condition: any, message?: string): asserts condition {

./packages/@textlint/kernel/src/context/TextlintRuleErrorImpl.ts
9:const assertTextlintRuleErrorDetail = (details: TextlintRuleErrorDetails) => {
60:        // padding assertion is done in locator function
99:            assertTextlintRuleErrorDetail(details);
```

### CODE REVIEW

**Review by azu — APPROVED** [review]
LGTM.

But, GitHub show "This branch cannot be rebased due to conflicts".
Update branch does not resolve this status. Fmm, What's happened?

image

**Comment by Sean0628** [comment]
Thank you for the review.
Oh... Did I do something wrong? I just merged master branch into head to resolve conflicts.

**Comment by azu** [comment]
Web UI is something wrong.

I've merged it via API and it's succussul😅

```bash
gh pr merge https://github.com/textlint/textlint/pull/990
```

**Comment by Sean0628** [comment]
Ah okay. Thanks anyway!

**Pull request merged**
